name: Build CPU Base Images

on:
  push:
    branches:
      - main
    paths:
      - 'base_image/cpu/**'
      - 'base_image/checker.sh'
      - '.github/workflows/build-base-images-cpu.yml'
jobs:
  build:
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.8', '3.9', '3.10', '3.11']
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Repository
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  
      - name: Extract Image Architecture
        id: extract-arch
        run: echo "arch=$(echo ${{ matrix.platform }} | sed 's|linux/||')" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./base_image
          file: ./base_image/cpu/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: wemoveon/base_images:python-${{ matrix.python_version }}-cpu-${{ env.arch }}
          build-args: |
            PYTHON_VERSION=${{ matrix.python_version }}
            TARGET_PLATFORM=${{ matrix.platform }}
          cache-to: type=registry,ref=wemoveon/base_images:python-${{ matrix.python_version }}-cpu-${{ env.arch }}-cache,mode=max,compression=zstd
          cache-from: type=registry,ref=wemoveon/base_images:python-${{ matrix.python_version }}-cpu-${{ env.arch }}-cache
