name: Build Base Images

on:
  push:
    branches:
      - main
jobs:
  build:
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cuda_version: [12.1.0]
        python_version: ['3.8', '3.9', '3.10', '3.11']
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Repository
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: wemoveon/base_images:python-${{ matrix.python_version }}-cuda-${{ matrix.cuda_version }}
          build-args: |
            CUDA_VERSION=${{ matrix.cuda_version }}
            PYTHON_VERSION=${{ matrix.python_version }}
            DRIVER_VERSION=550 # 550 is the colo driver ver
            TARGET_PLATFORM=${{ matrix.platform }}
